

spring:
  config:
    import: classpath:/application-secrets.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/authentication_project_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format_sql: true
  liquibase:
    change-log: classpath:db/master-changelog.xml
    enabled: true
    drop-first: false
    
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui: "/swagger-ui/index/html"