

spring:
  config:
    import: classpath:/application-secrets.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/authentication_project_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    change-log: classpath:db/master-changelog.xml
    enabled: true
    drop-first: false